---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

```{r}
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A  (Display the products that are most frequently added to the cart)

```{r}
# Count the number of times each product has been ordered and select the top 10.
instacart_top =
  instacart |>
  filter(!is.na(product_name)) |>
  count(product_name, sort = TRUE) |>
  head(10) |>
  mutate(product_name = fct_reorder(product_name, n))

instacart_top |>
  plot_ly(
    x = ~n, y = ~product_name, type = "bar", orientation = "h",
    marker = list(color = "steelblue")) |>
  layout(
    title = "Top 10 Most Frequently Ordered Products",
    xaxis = list(title = "The Number of Orders Placed"),
    yaxis = list(title = "Name of the Product"))
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B (Display the distribution of the sequence in which different departments' products are added to the cart)

```{r}
# Conduct a sampling of the department and limit the amount of data.
set.seed(123)
add_order =
  instacart |>
  filter(!is.na(add_to_cart_order)) |>
  group_by(department) |>
  slice_sample(n = 200) |>
  ungroup()

add_order |>
  plot_ly(
    x = ~department, y = ~add_to_cart_order, type = "box", color = ~department,
    boxpoints = "outliers") |>
  layout(
    title = "Distribution of Add-to-Cart Order by Department",
    xaxis = list(title = "Department", tickangle = 45),
    yaxis = list(title = "Order in Cart"),
    showlegend = FALSE
  )
```

### Chart C  (Display the trend of order quantities at different times of the day)

```{r}
# Count the number of orders by the hour
orders_hour =
  instacart |>
  filter(!is.na(order_hour_of_day), !is.na(order_id)) |>
  distinct(order_id, order_hour_of_day) |>
  count(order_hour_of_day, name = "order_count") |>
  arrange(order_hour_of_day)

orders_hour |>
  plot_ly(
    x = ~order_hour_of_day, y = ~order_count,
    type = "scatter",
    mode = "lines+markers",
    line = list(width = 3),
    marker = list(size = 8)) |>
  layout(
    title = "Order Frequency Throughout the Day",
    xaxis = list(title = "Hour of Day", tickmode = "linear", dtick = 2),
    yaxis = list(title = "Number of Orders"))
```

